### ISSUE TITLE
Binary release

### ISSUE THREAD

**Issue by predator8bit** [diasurgical/devilutionX#19]
I see the parent project had a 0.5 release, will there be any binary releases of this project for the people who can't/won't compile?

**Comment by AJenbo** [comment]
Yes, but things are changing a lot at the moment and we have a few short comings that we would like to take care of first.

64bit builds are currently not on feature parity with the 32bit builds so we are also debating if this should be included or not.

**Comment by andrewschott** [comment]
I would love to have a binary release, as getting this built on Fedora has been a futile effort.  I still am unable to get past getting cmake to create the makefile.

**Comment by AJenbo** [comment]
@andrewschott do you get any errors? We have recently updated the CMake scripts to where it should work more automatic as long as you have installed the needed dependencies.

**Comment by AJenbo** [comment]
@andrewschott Oh, that was fixed about 15 hours ago :) Since then we have also added basic UDP network support and the menu performance has been fixed. Let me know how it works out.

**Comment by AJenbo** [comment]
Arh that is good to hear, 32bit SDL on 64bit is broken on Ubuntu 18.04 so I haven't had a chance to verify it on a 64bit platform yet.

**Comment by sheepo99** [comment]
last week's build was compiling just fine for me on ubuntu, but right now I'm getting a missing libsodium message although I just installed it:

-- cotire 1.8.0 loaded.
-- Using 32-bit toolchain
-- Using 32-bit libraries from /usr/lib/i386-linux-gnu
CMake Error at /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find sodium (missing: sodium_LIBRARY_RELEASE
  sodium_LIBRARY_DEBUG)
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  CMake/Findsodium.cmake:227 (find_package_handle_standard_args)
  CMakeLists.txt:48 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/jvitorino/devilutionX-master/build32/CMakeFiles/CMakeOutput.log".
See also "/home/jvitorino/devilutionX-master/build32/CMakeFiles/CMakeError.log".

**Comment by AJenbo** [comment]
@sheepo99 thanks for reporting, the issue should now be solved.

**Comment by sheepo99** [comment]
Hi Ajenbo,

Just tried to recompile latest source. Issue persists. Error msg:

-- cotire 1.8.0 loaded.
-- Using 32-bit toolchain
-- Using 32-bit libraries from /usr/lib/i386-linux-gnu
-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is GNU 7.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found SDL2: /usr/lib/i386-linux-gnu/libSDL2main.a;/usr/lib/i386-linux-gnu/libSDL2.so;-lpthread  
-- Found SDL2_ttf: /usr/lib/i386-linux-gnu/libSDL2_ttf.so (found version "2.0.14") 
-- Found SDL2_mixer: /usr/lib/i386-linux-gnu/libSDL2_mixer.so (found version "2.0.2") 
CMake Error at /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find sodium (missing: sodium_LIBRARY_RELEASE
  sodium_LIBRARY_DEBUG)
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  CMake/Findsodium.cmake:227 (find_package_handle_standard_args)
  CMakeLists.txt:48 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/jvitorino/Desktop/devilutionX-master/build32/CMakeFiles/CMakeOutput.log".
See also "/home/jvitorino/Desktop/devilutionX-master/build32/CMakeFiles/CMakeError.log".

**Comment by sheepo99** [comment]
@AJenbo I have the latest version of libsodium-dev:i386 installed (just checked for both dev and non-dev libs), and the issue still persists. I am attaching the error log.

For the record, I am running Xubuntu 18.04 bionic 64bit version.

[CMakeError.log](https://github.com/diasurgical/devilutionX/files/2825377/CMakeError.log)

**Comment by AJenbo** [comment]
Could you try deleting everything in the build32 folder and use the following command:
`cmake .. --trace --debug-output`

**Comment by sheepo99** [comment]
@AJenbo here are the logs after I tried that. Please note I added FORCE32=1 along with the trace and debug cmds.

[CMakeError.log](https://github.com/diasurgical/devilutionX/files/2827425/CMakeError.log)
[CMakeOutput.log](https://github.com/diasurgical/devilutionX/files/2827426/CMakeOutput.log)

**Comment by sheepo99** [comment]
FIXED IT! Turns out I had only installed libsodium-dev:i386 and I needed the amd64 version as well. I would advise to add it to the readme instructions.

**Comment by AJenbo** [comment]
Thanks good to know :)

**Comment by predator8bit** [comment]
Since there is not going to be a release for a bit, I feel like I should point out that the "Download Devilution" button under the "How To Play:" section of the readme is 404.

**Comment by ApertureSecurity** [comment]
Yeah I want to make a release . The release I have is so old though.

**Comment by AJenbo** [comment]
There should be a release in about a week

**Comment by AJenbo** [comment]
Fixed: https://github.com/diasurgical/devilutionX/releases/tag/0.1.0
