### ISSUE TITLE
Cursor confined to 640x480??? Top right. Corrects by switching app then back to DevX

### ISSUE THREAD

**Issue by DrGonzo564** [diasurgical/devilutionX#4251]
MacOS 12.3 / DevilutionX 1.4 Test Build #6717 / Download

**Describe**
When I launch the game my cursor is stuck in the top right of the screen in what looks like maybe a 640x480 box?

**To Reproduce**
1. Launch DevilutionX
2. Cursor is stuck in top right box/

**Additional context**
When I switch out of the app and then back to DevX it fixes the problem.

https://user-images.githubusercontent.com/82344993/160358054-56df02f5-a312-4bec-8e22-0fc50409a11c.mov

**Comment by AJenbo** [comment]
@bubio are you able to replicate this?

**Comment by bubio** [comment]
I can't replicate it

**Comment by bubio** [comment]
I think the DPI calculation is not correct for iMac.
@DrGonzo564 
Is the display set to 2560 x 1440 ?

**Comment by DrGonzo564** [comment]
My iMacs display  is set to 5120x2880 I’m not sure what I have the game set at tho I’ll have to check when I get home later.

**Comment by bubio** [comment]
@DrGonzo564 
Let me ask you a few more questions.

Q1. The resolution settings for the iMac 5K are

1600 x 900
2048 x 1152
2560 x 1440
2880 x 1620
3200 x 1800

I would think you would choose one of the following, no?

Q2.Cursor jumps to bottom right corner of screen when selecting item in inventory #4217
Is this also not fixed?

**Comment by DrGonzo564** [comment]
@bubio 

Q1. So my resolution in game is set to 640x480 everything else makes the game window smaller

Q2. #4217 is fixed now no issues when selecting items in inventory.

**Comment by StephenCWills** [comment]
You're still experiencing this issue, right? Did you mean to close this?

**Comment by DrGonzo564** [comment]
Yes I’m still experiencing this. I’m sry if I closed it by accident I’m new to GitHub whoops

**Comment by bubio** [comment]
> @bubio
> 
> Q1. So my resolution in game is set to 640x480 everything else makes the game window smaller
> 
> Q2. #4217 is fixed now no issues when selecting items in inventory.

Q1 refers to macOS system settings.
![issue_4251_1](https://user-images.githubusercontent.com/78299054/160641146-1d43ad8d-8d56-43cd-bd22-78bf3e3cc138.png)

**Comment by DrGonzo564** [comment]
Its a 5k iMac display is 5120x2880 like I first said... <img width="1290" alt="Screen Shot 2022-03-29 at 8 03 51 AM" src="https://user-images.githubusercontent.com/82344993/160642748-d20a3225-8fec-47be-9e43-659bf85df572.png">

**Comment by bubio** [comment]
> Its a 5k iMac display is 5120x2880 like I first said...

It is the native resolution.
The Resolution item is set to "Default to Display", so you are using 2560 x 1440.

**Comment by DrGonzo564** [comment]
Yes 2560 x 1440 sry When I went to display it just said the other number my bad. Silly iMacs

**Comment by DrGonzo564** [comment]
@bubio

Hey I tried but the app wont even open it keeps crashing :(

![Screen Shot 2022-03-31 at 7 20 27 AM](https://user-images.githubusercontent.com/82344993/161162469-b9a8bf99-f8e1-467b-92d9-3a17121a78ad.jpg)
![Screen Shot 2022-03-31 at 7 20 40 AM](https://user-images.githubusercontent.com/82344993/161162473-c796ab5f-b558-4af4-be69-5d93824debd3.jpg)
![Screen Shot 2022-03-31 at 7 20 46 AM](https://user-images.githubusercontent.com/82344993/161162480-af23ebb7-70ce-4322-aa62-e3be980a59a1.jpg)

**Comment by AJenbo** [comment]
The issue appears to be that the build does not include dependencies like libpng, you could copy them from the other test version (right click show content, and copy the frameworks folder)

**Comment by DrGonzo564** [comment]
So I copied the frameworks folder from the old version to the new one and its still crashing :(
<img width="1248" alt="Screen Shot 2022-03-31 at 6 35 41 PM" src="https://user-images.githubusercontent.com/82344993/161177657-b2641fc5-599e-4834-a4fa-877c32b9d5e4.png">
<img width="1247" alt="Screen Shot 2022-03-31 at 6 35 50 PM" src="https://user-images.githubusercontent.com/82344993/161177664-28554547-6f3f-40df-a977-d998fa8e5600.png">

**Comment by bubio** [comment]
I'm sorry. I will rebuild.

**Comment by bubio** [comment]
[DevilutionX.zip](https://github.com/diasurgical/devilutionX/files/8394037/DevilutionX.zip)

I think this will work.

**Comment by DrGonzo564** [comment]
Thanks... Yah so this version didn't crash but its still having the same bug where the cursor is stuck in the top right in like a 640x480 window.

**Comment by bubio** [comment]
...then it seems to be a different issue.

**Comment by bubio** [comment]
[DevilutionX.zip](https://github.com/diasurgical/devilutionX/files/8398336/DevilutionX.zip)

Would you be willing to try this?
The process I changed in PR #4244 is in two places, the last time you tried it was to revert one place.
This time, I have reverted both places.
This should cause issue #4217.
Just to confirm, this issue did not occur with [gamepad] Fix managing belt MacOSX #6699, but now occurs with Fixed issue #4217 MacOSX #6703 build, correct?

**Comment by DrGonzo564** [comment]
Hey so just tried that version and its still confined to 640x480 :(

Yah so I first had issue #4217 they fixed that but then after that got fixed I started getting the new 640x480 issue :( hope that makes sense.

**Comment by bubio** [comment]
@DrGonzo564
Thanks for trying.

PR #4244 does not seem to be the cause.

Could you try the build of [gamepad] Fix managing belt MacOSX #6699 again?
It may not be due to changes in DevilutionX, but to external factors such as OS updates.

**Comment by DrGonzo564** [comment]
So just tried #6699 and still having the 640x480 problem

**Comment by bubio** [comment]
I still don't think PR #4244 is relevant.

**Comment by StephenCWills** [comment]
I just wanted to pop in to say that I have a pretty strong suspicion this is an SDL issue. However, I can't really gather any evidence since I don't have access to a Mac with high DPI support for testing. Furthermore, I have been browsing SDL issues and PRs for the last several days, but I haven't found anything relevant reported there.

Regardless, I don't believe the game is doing anything in particular to trap the mouse in a specific region of the screen. It seems pretty clear that this is a scaling issue. I would be very curious to know if any of the main menu options are clickable when the mouse cursor is confined. Try clicking around the center of the confined region to see if you can enter any menus. That is to say...

![image](https://user-images.githubusercontent.com/9203145/161357456-71957e38-0d35-4bb5-848e-bcf734ffd5d7.png)

**Comment by DrGonzo564** [comment]
Clicking around and I can’t access any of the menu items by clicking all over :( I can mouse scroll tho and use the arrow keys but clicking wont get me access to any of the menus :(

**Comment by StephenCWills** [comment]
Not quite what I expected, but it seems to confirm that mouse button events are providing the properly scaled coordinates in spite of the confinement issue. 🤔

**Comment by StephenCWills** [comment]
Oh, I reproduced this at normal DPI by turning on the `Grab Input` setting.

**Comment by bubio** [comment]
> Oh, I reproduced this at normal DPI by turning on the `Grab Input` setting.

I reproduced it too.

**Comment by bubio** [comment]
If you change the setting in the menu, use the
```c++
SDL_SetWindowGrab(ghMainWnd, *sgOptions.Gameplay.grabInput ? SDL_TRUE : SDL_FALSE);
```


https://github.com/diasurgical/devilutionX/blob/7e83aa1429a2b53fe01ac12c0dd909912a3eb09e/Source/options.cpp#L239

On the other hand, when it is started, the SDL_CreateWindow flag is used.

```c++
if (*sgOptions.Gameplay.grabInput) {
	flags |= SDL_WINDOW_INPUT_GRABBED;
}

ghMainWnd = SDL_CreateWindow(lpWindowName, SDL_WINDOWPOS_UNDEFINED, SDL_WINDOWPOS_UNDEFINED, windowSize.width, windowSize.height, flags);
```

There seems to be a problem with the behavior of SDL_WINDOW_INPUT_GRABBED.

**Comment by glebm** [comment]
Looks related: https://github.com/libsdl-org/SDL/issues/962

From that bug:
> I believe I've found a workaround - instead of passing SDL_WINDOW_INPUT_GRABBED to SDL_CreateWindow(), calling SDL_SetWindowGrab() immediately after SDL_CreateWindow() works.

**Comment by DrGonzo564** [comment]
Thanks for fixing :D

**Comment by DrGonzo564** [comment]
Might of got the resolution wrong I’ll double check when I get home.

**Comment by DrGonzo564** [comment]
Hey just tried the one you sent but it wont open keeps crashing

**Comment by AJenbo** [comment]
try 1.4.1
