### ISSUE TITLE
[improvement request] Integrate widescreen loading screen for the town

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#5922]
As already discussed in #5885 the graphic for the town (church entry) used for returning to the town as follow up.
Please let me know if you like the result.

Cutout 1366x480:
![000325 3709905922_church_outside_borders](https://user-images.githubusercontent.com/45902449/227609232-c85212d6-ddcb-4ae7-ad9e-875f4f84ddc4.png)

Full image 1366x480:
![000325 3709905922_church_outside_full](https://user-images.githubusercontent.com/45902449/227609261-fc2afcbc-4c25-4697-884c-3ff6df8c67b5.png)

**Comment by AJenbo** [comment]
Oh wow that is a lot of tree out of almost nothing, I like it :)

**Comment by AJenbo** [comment]
Fixed https://github.com/diasurgical/devilutionX/pull/5923 no real changes, just the usual tiny edge patches and conversion to 8bit

**Comment by Chance4us** [comment]
I still have the old graphics in the game, is there a delay in uploading the graphics?

**Comment by AJenbo** [comment]
no

**Comment by StephenCWills** [comment]
Did we forget to add it here?

https://github.com/diasurgical/devilutionX/blob/839690a74facabee22f00cbe5481247ef6d0696d/CMake/Assets.cmake#L165-L170

**Comment by AJenbo** [comment]
Yeah i think that's it
