### ISSUE TITLE
[Russian] text out of bounds in unique item stat window

### ISSUE THREAD

**Issue by Riccila** [diasurgical/devilutionX#7651]
### Feature Type

Bug

### Describe

<img width="1470" alt="Скрин_1" src="https://github.com/user-attachments/assets/58fee3d0-6143-4c42-b897-002adf66b5d5" />
<img width="1470" alt="Скрин_2" src="https://github.com/user-attachments/assets/6010c255-c92f-4b92-af03-a3606b855ec6" />
Good evening! Dear developers. There are two screenshots in the attachment. Is it possible to correct the position of the text in the description of the objects (language Russian). Specifically these, as well as possible descriptions of other unique things. Thank you in advance!

**Comment by MaderatorCreator** [comment]
--- EN ---
 
1. The name of the bug report should also be in English.
2. I fixed it in the new version of the Russian localization, losing the word "restore" to "restore." You can test it in the project builds or wait for the new version.
I recommend closing this issue, because the problem has already been solved. If you have any questions about the Russian localization, write to me on social networks - Discord, Telegram, VKontakte. Everywhere I am @Maderator3000

UPD: with the inscription about absorbing damage from traps, I will also decide in the future.

--- RU ---

1. Название сообщения о баге тоже должно быть на английском
2. Я это пофиксил в новой версии русской локализации, утратив слово "восстановление" до "восст.". Протестировать можно в билдах проекта или ждать новую версию.

Рекомендую закрыть это issue, т.к. проблема уже решена. По любым вопросам касательно русской локализации пиши мне в соц. сети - Дискорд, Телеграм, ВКонтакте. Везде я @Maderator_Creator

UPD: с надписью о поглощении урона от ловушек тоже в дальнейшем порешаю.

**Comment by qndel** [comment]
@Maderator3000 we use english here

**Comment by Maderator3000** [comment]
> @Maderator3000 we use english here

I know, I just see that the guy is Russian and for his convenience I answered in Russian. In short: the problem is partially solved in the updated Russian localization, which I updated. A little later I will try to fix a couple more errors related to Russian localization that I know about.

**Comment by AJenbo** [comment]
> I know, I just see that the guy is Russian and for his convenience I answered in Russian.

Pretty hard for us to know to close the issue or not if we can't understand what is being said.

**Comment by Maderator3000** [comment]
> Pretty hard for us to know to close the issue or not if we can't understand what is being said.

Oh, sorry. I'll take this into account in the future

**Comment by AJenbo** [comment]
> UPD: I will also solve the problem with the inscription about absorbing damage from traps in the future.

Lets keep it op till this part is also solve. Thanks for handeling it and the quick response.

@Riccila thank you for the nice bug report

**Comment by Maderator3000** [comment]
Got it, tomorrow after the exam (evening-night Moscow time) I'll fix the problem with the text about traps 🙃

**Comment by glebm** [comment]
A non-Russian specific issue here is that it clearly attempts to wrap the text but does so within incorrect boundaries. We should fix the boundaries passed when drawing the unique item info text.

**Comment by glebm** [comment]
We have:

https://github.com/diasurgical/devilutionX/blob/ccbf0fc9a2813a6f33db06fb3d3c05f6c2c4150f/Source/items.cpp#L4090

but the actual info window position is calculate not absolutely but relative to the inventory:

https://github.com/diasurgical/devilutionX/blob/ccbf0fc9a2813a6f33db06fb3d3c05f6c2c4150f/Source/items.cpp#L1748

**Comment by glebm** [comment]
The fix might be to simply return `panelX` on this line instead of what it's doing currently:

https://github.com/diasurgical/devilutionX/blob/ccbf0fc9a2813a6f33db06fb3d3c05f6c2c4150f/Source/items.cpp#L1762

**Comment by Maderator3000** [comment]
Should this be fixed in the localization itself or will it be fixed in the code?

**Comment by Maderator3000** [comment]
> We should fix the boundaries passed to the text rendering function when drawing the unique item info text.

Should I fix the item's stat about absorbing half of the damage from traps at the localization level or wait for code-level edits?

**Comment by AJenbo** [comment]
wait for code

**Comment by StephenCWills** [comment]
> The text rectangle needs to be adjusted to fit within the box.

I'm not sure how the width of that bounding box compares to the info panel, but perhaps we should also consider allowing the text renderer to adjust character spacing.

![Screenshot_20250114-054817](https://github.com/user-attachments/assets/92e73a5a-4495-4466-b946-ce8b4a5caa13)

That said, it appears the last character gets cut off? Might need to look into that as well...

**Comment by Riccila** [comment]
Dear developers. Two more screenshots. As I understand it, the problem is similar. It may have already been fixed. But I decided to reset the information anyway, in case it helps.

<img width="1470" alt="Image" src="https://github.com/user-attachments/assets/c7b8460a-809b-4dd8-b0ad-0a8d387d809d" />
<img width="1470" alt="Image" src="https://github.com/user-attachments/assets/adea82d9-a5c8-47c2-8774-68fba4e91144" />

**Comment by Riccila** [comment]
<img width="1470" alt="Image" src="https://github.com/user-attachments/assets/6ec65e5f-736f-4ec6-a4c6-3bac757115a3" />

**Comment by Riccila** [comment]
<img width="1470" alt="Image" src="https://github.com/user-attachments/assets/341f5d1c-9bff-44c2-80c4-2443abf6015e" />

**Comment by StephenCWills** [comment]
To be clear, my screenshot was taken using a fairly recent test build. The screenshots Riccila shared just now appear to have been taken in a release build, because the text is rendering out of bounds to the left. I believe that behavior may have been fixed already since I didn't see it in the test build.

My thinking is that it may be a good idea to compute text width based on the widest line rather than stopping at the first newline character.

https://github.com/diasurgical/devilutionX/blob/f7603b76c96c98538d8cfc25d807114f9557c1aa/Source/engine/render/text_render.cpp#L513-L514

**Comment by kphoenix137** [comment]
This may be a good time to implement floating info boxes for item information, perhaps as the only option. We can display only the item name in the control panel, then use a floating box with the panel/unique box information that dynamically stretches with the contents. The size limitations of the panel box and unique info box are just too restrictive and problematic, and aren't good for modding either.

**Comment by AJenbo** [comment]
Any time would be a good time for that :)

**Comment by Riccila** [comment]
Dear developers, please note one more fact - I am attaching two screenshots. On one, it seems to me, the text is scaled and everything is perfectly visible on the other, it is not. In general, if a solution to the problem is found, it will be great. If everything has already been fixed, then consider that I just signaled.
